package CMS;


/**
* CMS/_CustomerCareServiceStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idl/cms.idl
* Friday, April 18, 2025 1:35:57 AM ICT
*/

public class _CustomerCareServiceStub extends org.omg.CORBA.portable.ObjectImpl implements CMS.CustomerCareService
{

  public String createTicket (CMS.CustomerCare ticket)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("createTicket", true);
                CMS.CustomerCareHelper.write ($out, ticket);
                $in = _invoke ($out);
                String $result = $in.read_string ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return createTicket (ticket        );
            } finally {
                _releaseReply ($in);
            }
  } // createTicket

  public boolean updateTicket (String ticketId, CMS.CustomerCare updateTicket)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("updateTicket", true);
                $out.write_string (ticketId);
                CMS.CustomerCareHelper.write ($out, updateTicket);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return updateTicket (ticketId, updateTicket        );
            } finally {
                _releaseReply ($in);
            }
  } // updateTicket

  public CMS.CustomerCare getTicketInfo (String ticketId)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getTicketInfo", true);
                $out.write_string (ticketId);
                $in = _invoke ($out);
                CMS.CustomerCare $result = CMS.CustomerCareHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getTicketInfo (ticketId        );
            } finally {
                _releaseReply ($in);
            }
  } // getTicketInfo

  public CMS.CustomerCare[] getCustomerTicket (String customerId)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getCustomerTicket", true);
                $out.write_string (customerId);
                $in = _invoke ($out);
                CMS.CustomerCare $result[] = CMS.CustomerCareSeqHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getCustomerTicket (customerId        );
            } finally {
                _releaseReply ($in);
            }
  } // getCustomerTicket

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:CMS/CustomerCareService:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _CustomerCareServiceStub
