package CMS;


/**
* CMS/CustomerUpdateServiceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idl/cms.idl
* Friday, April 18, 2025 1:35:57 AM ICT
*/

public interface CustomerUpdateServiceOperations 
{
  boolean updateCustomerInfo (String customerId, CMS.CustomerInfo newInfo);
  boolean updateStatus (String customerId, String newStatus);
  void logCustomerChange (String customerId, String changeType);
} // interface CustomerUpdateServiceOperations
