package CMS;


/**
* CMS/CustomerUpdateServicePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idl/cms.idl
* Friday, April 18, 2025 1:35:57 AM ICT
*/

public abstract class CustomerUpdateServicePOA extends org.omg.PortableServer.Servant
 implements CMS.CustomerUpdateServiceOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable<String, Integer> _methods = new java.util.Hashtable<>();
  static
  {
    _methods.put ("updateCustomerInfo", new java.lang.Integer (0));
    _methods.put ("updateStatus", new java.lang.Integer (1));
    _methods.put ("logCustomerChange", new java.lang.Integer (2));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // CMS/CustomerUpdateService/updateCustomerInfo
       {
         String customerId = in.read_string ();
         CMS.CustomerInfo newInfo = CMS.CustomerInfoHelper.read (in);
         boolean $result = false;
         $result = this.updateCustomerInfo (customerId, newInfo);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 1:  // CMS/CustomerUpdateService/updateStatus
       {
         String customerId = in.read_string ();
         String newStatus = in.read_string ();
         boolean $result = false;
         $result = this.updateStatus (customerId, newStatus);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 2:  // CMS/CustomerUpdateService/logCustomerChange
       {
         String customerId = in.read_string ();
         String changeType = in.read_string ();
         this.logCustomerChange (customerId, changeType);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:CMS/CustomerUpdateService:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public CustomerUpdateService _this() 
  {
    return CustomerUpdateServiceHelper.narrow(
    super._this_object());
  }

  public CustomerUpdateService _this(org.omg.CORBA.ORB orb) 
  {
    return CustomerUpdateServiceHelper.narrow(
    super._this_object(orb));
  }


} // class CustomerUpdateServicePOA
