package CMS;

/**
* CMS/CustomerInfoServiceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idl/cms.idl
* Friday, April 18, 2025 1:35:57 AM ICT
*/

public final class CustomerInfoServiceHolder implements org.omg.CORBA.portable.Streamable
{
  public CMS.CustomerInfoService value = null;

  public CustomerInfoServiceHolder ()
  {
  }

  public CustomerInfoServiceHolder (CMS.CustomerInfoService initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CMS.CustomerInfoServiceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CMS.CustomerInfoServiceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CMS.CustomerInfoServiceHelper.type ();
  }

}
