package CMS;


/**
* CMS/CustomerInfoServiceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idl/cms.idl
* Friday, April 18, 2025 1:35:57 AM ICT
*/

public interface CustomerInfoServiceOperations 
{
  CMS.CustomerInfo getCustomer (String customerId);
  CMS.CustomerInfo[] searchCustomer (String criteria);
  boolean addCustomer (CMS.CustomerInfo customer);
  CMS.CustomerInfo[] getAllCustomer ();
} // interface CustomerInfoServiceOperations
