package CMS;


/**
* CMS/CustomerInfoServicePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idl/cms.idl
* Friday, April 18, 2025 1:35:56 AM ICT
*/

public abstract class CustomerInfoServicePOA extends org.omg.PortableServer.Servant
 implements CMS.CustomerInfoServiceOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable<String, Integer> _methods = new java.util.Hashtable<>();
  static
  {
    _methods.put ("getCustomer", new java.lang.Integer (0));
    _methods.put ("searchCustomer", new java.lang.Integer (1));
    _methods.put ("addCustomer", new java.lang.Integer (2));
    _methods.put ("getAllCustomer", new java.lang.Integer (3));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // CMS/CustomerInfoService/getCustomer
       {
         String customerId = in.read_string ();
         CMS.CustomerInfo $result = null;
         $result = this.getCustomer (customerId);
         out = $rh.createReply();
         CMS.CustomerInfoHelper.write (out, $result);
         break;
       }

       case 1:  // CMS/CustomerInfoService/searchCustomer
       {
         String criteria = in.read_string ();
         CMS.CustomerInfo $result[] = null;
         $result = this.searchCustomer (criteria);
         out = $rh.createReply();
         CMS.CustomerInfoSeqHelper.write (out, $result);
         break;
       }

       case 2:  // CMS/CustomerInfoService/addCustomer
       {
         CMS.CustomerInfo customer = CMS.CustomerInfoHelper.read (in);
         boolean $result = false;
         $result = this.addCustomer (customer);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 3:  // CMS/CustomerInfoService/getAllCustomer
       {
         CMS.CustomerInfo $result[] = null;
         $result = this.getAllCustomer ();
         out = $rh.createReply();
         CMS.CustomerInfoSeqHelper.write (out, $result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:CMS/CustomerInfoService:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public CustomerInfoService _this() 
  {
    return CustomerInfoServiceHelper.narrow(
    super._this_object());
  }

  public CustomerInfoService _this(org.omg.CORBA.ORB orb) 
  {
    return CustomerInfoServiceHelper.narrow(
    super._this_object(orb));
  }


} // class CustomerInfoServicePOA
