package CMS;


/**
* CMS/CustomerCareServiceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idl/cms.idl
* Friday, April 18, 2025 1:35:57 AM ICT
*/

public interface CustomerCareServiceOperations 
{
  String createTicket (CMS.CustomerCare ticket);
  boolean updateTicket (String ticketId, CMS.CustomerCare updateTicket);
  CMS.CustomerCare getTicketInfo (String ticketId);
  CMS.CustomerCare[] getCustomerTicket (String customerId);
} // interface CustomerCareServiceOperations
