package CMS;


/**
* CMS/CustomerCareServicePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idl/cms.idl
* Friday, April 18, 2025 1:35:57 AM ICT
*/

public abstract class CustomerCareServicePOA extends org.omg.PortableServer.Servant
 implements CMS.CustomerCareServiceOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable<String, Integer> _methods = new java.util.Hashtable<String, Integer>();
  static
  {
    _methods.put ("createTicket", new java.lang.Integer (0));
    _methods.put ("updateTicket", new java.lang.Integer (1));
    _methods.put ("getTicketInfo", new java.lang.Integer (2));
    _methods.put ("getCustomerTicket", new java.lang.Integer (3));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // CMS/CustomerCareService/createTicket
       {
         CMS.CustomerCare ticket = CMS.CustomerCareHelper.read (in);
         String $result = null;
         $result = this.createTicket (ticket);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // CMS/CustomerCareService/updateTicket
       {
         String ticketId = in.read_string ();
         CMS.CustomerCare updateTicket = CMS.CustomerCareHelper.read (in);
         boolean $result = false;
         $result = this.updateTicket (ticketId, updateTicket);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 2:  // CMS/CustomerCareService/getTicketInfo
       {
         String ticketId = in.read_string ();
         CMS.CustomerCare $result = null;
         $result = this.getTicketInfo (ticketId);
         out = $rh.createReply();
         CMS.CustomerCareHelper.write (out, $result);
         break;
       }

       case 3:  // CMS/CustomerCareService/getCustomerTicket
       {
         String customerId = in.read_string ();
         CMS.CustomerCare $result[] = null;
         $result = this.getCustomerTicket (customerId);
         out = $rh.createReply();
         CMS.CustomerCareSeqHelper.write (out, $result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:CMS/CustomerCareService:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public CustomerCareService _this() 
  {
    return CustomerCareServiceHelper.narrow(
    super._this_object());
  }

  public CustomerCareService _this(org.omg.CORBA.ORB orb) 
  {
    return CustomerCareServiceHelper.narrow(
    super._this_object(orb));
  }


} // class CustomerCareServicePOA
