package CMS;


/**
* CMS/CustomerInfoServiceHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idl/cms.idl
* Friday, April 18, 2025 1:35:57 AM ICT
*/

abstract public class CustomerInfoServiceHelper
{
  private static String  _id = "IDL:CMS/CustomerInfoService:1.0";

  public static void insert (org.omg.CORBA.Any a, CMS.CustomerInfoService that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static CMS.CustomerInfoService extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (CMS.CustomerInfoServiceHelper.id (), "CustomerInfoService");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static CMS.CustomerInfoService read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_CustomerInfoServiceStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, CMS.CustomerInfoService value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static CMS.CustomerInfoService narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof CMS.CustomerInfoService)
      return (CMS.CustomerInfoService)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      CMS._CustomerInfoServiceStub stub = new CMS._CustomerInfoServiceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static CMS.CustomerInfoService unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof CMS.CustomerInfoService)
      return (CMS.CustomerInfoService)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      CMS._CustomerInfoServiceStub stub = new CMS._CustomerInfoServiceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
