package CMS;


/**
* CMS/CustomerInfoSeqHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idl/cms.idl
* Friday, April 18, 2025 1:35:56 AM ICT
*/

public final class CustomerInfoSeqHolder implements org.omg.CORBA.portable.Streamable
{
  public CMS.CustomerInfo value[] = null;

  public CustomerInfoSeqHolder ()
  {
  }

  public CustomerInfoSeqHolder (CMS.CustomerInfo[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CMS.CustomerInfoSeqHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CMS.CustomerInfoSeqHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CMS.CustomerInfoSeqHelper.type ();
  }

}
