package CMS;


/**
* CMS/CustomerUpdateService.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idl/cms.idl
* Friday, April 18, 2025 1:35:57 AM ICT
*/

public interface CustomerUpdateService extends CustomerUpdateServiceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface CustomerUpdateService
