package CMS;


/**
* CMS/CustomerCare.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idl/cms.idl
* Friday, April 18, 2025 1:35:56 AM ICT
*/

public final class CustomerCare implements org.omg.CORBA.portable.IDLEntity
{
  public String ticketId = null;
  public String customerId = null;
  public String issue = null;
  public String status = null;
  public String priority = null;
  public String resolution = null;

  public CustomerCare ()
  {
  } // ctor

  public CustomerCare (String _ticketId, String _customerId, String _issue, String _status, String _priority, String _resolution)
  {
    ticketId = _ticketId;
    customerId = _customerId;
    issue = _issue;
    status = _status;
    priority = _priority;
    resolution = _resolution;
  } // ctor

} // class CustomerCare
