package CMS;


/**
* CMS/CustomerCareSeqHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idl/cms.idl
* Friday, April 18, 2025 1:35:56 AM ICT
*/

public final class CustomerCareSeqHolder implements org.omg.CORBA.portable.Streamable
{
  public CMS.CustomerCare value[] = null;

  public CustomerCareSeqHolder ()
  {
  }

  public CustomerCareSeqHolder (CMS.CustomerCare[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CMS.CustomerCareSeqHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CMS.CustomerCareSeqHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CMS.CustomerCareSeqHelper.type ();
  }

}
