package CMS;

/**
* CMS/CustomerCareServiceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idl/cms.idl
* Friday, April 18, 2025 1:35:57 AM ICT
*/

public final class CustomerCareServiceHolder implements org.omg.CORBA.portable.Streamable
{
  public CMS.CustomerCareService value = null;

  public CustomerCareServiceHolder ()
  {
  }

  public CustomerCareServiceHolder (CMS.CustomerCareService initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CMS.CustomerCareServiceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CMS.CustomerCareServiceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CMS.CustomerCareServiceHelper.type ();
  }

}
