package CMS;


/**
* CMS/CustomerUpdateServiceHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idl/cms.idl
* Friday, April 18, 2025 1:35:57 AM ICT
*/

abstract public class CustomerUpdateServiceHelper
{
  private static String  _id = "IDL:CMS/CustomerUpdateService:1.0";

  public static void insert (org.omg.CORBA.Any a, CMS.CustomerUpdateService that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static CMS.CustomerUpdateService extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (CMS.CustomerUpdateServiceHelper.id (), "CustomerUpdateService");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static CMS.CustomerUpdateService read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_CustomerUpdateServiceStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, CMS.CustomerUpdateService value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static CMS.CustomerUpdateService narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof CMS.CustomerUpdateService)
      return (CMS.CustomerUpdateService)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      CMS._CustomerUpdateServiceStub stub = new CMS._CustomerUpdateServiceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static CMS.CustomerUpdateService unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof CMS.CustomerUpdateService)
      return (CMS.CustomerUpdateService)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      CMS._CustomerUpdateServiceStub stub = new CMS._CustomerUpdateServiceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
