package CMS;

/**
* CMS/CustomerInfoHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idl/cms.idl
* Friday, April 18, 2025 1:35:56 AM ICT
*/

public final class CustomerInfoHolder implements org.omg.CORBA.portable.Streamable
{
  public CMS.CustomerInfo value = null;

  public CustomerInfoHolder ()
  {
  }

  public CustomerInfoHolder (CMS.CustomerInfo initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CMS.CustomerInfoHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CMS.CustomerInfoHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CMS.CustomerInfoHelper.type ();
  }

}
