package CMS;


/**
* CMS/CustomerInfo.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idl/cms.idl
* Friday, April 18, 2025 1:35:56 AM ICT
*/

public final class CustomerInfo implements org.omg.CORBA.portable.IDLEntity
{
  public String customerId = null;
  public String customerName = null;
  public String customerEmail = null;
  public String customerPhone = null;
  public String customerAddress = null;
  public String customerStatus = null;

  public CustomerInfo ()
  {
  } // ctor

  public CustomerInfo (String _customerId, String _customerName, String _customerEmail, String _customerPhone, String _customerAddress, String _customerStatus)
  {
    customerId = _customerId;
    customerName = _customerName;
    customerEmail = _customerEmail;
    customerPhone = _customerPhone;
    customerAddress = _customerAddress;
    customerStatus = _customerStatus;
  } // ctor

} // class CustomerInfo
