package CMS;

/**
* CMS/CustomerUpdateServiceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idl/cms.idl
* Friday, April 18, 2025 1:35:57 AM ICT
*/

public final class CustomerUpdateServiceHolder implements org.omg.CORBA.portable.Streamable
{
  public CMS.CustomerUpdateService value = null;

  public CustomerUpdateServiceHolder ()
  {
  }

  public CustomerUpdateServiceHolder (CMS.CustomerUpdateService initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CMS.CustomerUpdateServiceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CMS.CustomerUpdateServiceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CMS.CustomerUpdateServiceHelper.type ();
  }

}
