package CMS;


/**
* CMS/EmailCampaign.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idl/cms.idl
* Friday, April 18, 2025 1:35:56 AM ICT
*/

public final class EmailCampaign implements org.omg.CORBA.portable.IDLEntity
{
  public String campaignId = null;
  public String title = null;
  public String content = null;
  public String targetSegment = null;
  public String status = null;

  public EmailCampaign ()
  {
  } // ctor

  public EmailCampaign (String _campaignId, String _title, String _content, String _targetSegment, String _status)
  {
    campaignId = _campaignId;
    title = _title;
    content = _content;
    targetSegment = _targetSegment;
    status = _status;
  } // ctor

} // class EmailCampaign
