package CMS;


/**
* CMS/EmailMarketingServicePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idl/cms.idl
* Friday, April 18, 2025 1:35:57 AM ICT
*/

public abstract class EmailMarketingServicePOA extends org.omg.PortableServer.Servant
 implements CMS.EmailMarketingServiceOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable<String, Integer> _methods = new java.util.Hashtable<>();
  static
  {
    _methods.put ("createCampaign", new java.lang.Integer (0));
    _methods.put ("sendCampaign", new java.lang.Integer (1));
    _methods.put ("getCustomerSegment", new java.lang.Integer (2));
    _methods.put ("getCampaign", new java.lang.Integer (3));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // CMS/EmailMarketingService/createCampaign
       {
         CMS.EmailCampaign campaign = CMS.EmailCampaignHelper.read (in);
         boolean $result = false;
         $result = this.createCampaign (campaign);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 1:  // CMS/EmailMarketingService/sendCampaign
       {
         String campaignId = in.read_string ();
         boolean $result = false;
         $result = this.sendCampaign (campaignId);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 2:  // CMS/EmailMarketingService/getCustomerSegment
       {
         String segmentCriteria = in.read_string ();
         String $result[] = null;
         $result = this.getCustomerSegment (segmentCriteria);
         out = $rh.createReply();
         CMS.StringSeqHelper.write (out, $result);
         break;
       }

       case 3:  // CMS/EmailMarketingService/getCampaign
       {
         String campaignId = in.read_string ();
         CMS.EmailCampaign $result = null;
         $result = this.getCampaign (campaignId);
         out = $rh.createReply();
         CMS.EmailCampaignHelper.write (out, $result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:CMS/EmailMarketingService:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public EmailMarketingService _this() 
  {
    return EmailMarketingServiceHelper.narrow(
    super._this_object());
  }

  public EmailMarketingService _this(org.omg.CORBA.ORB orb) 
  {
    return EmailMarketingServiceHelper.narrow(
    super._this_object(orb));
  }


} // class EmailMarketingServicePOA
