package CMS;

/**
* CMS/EmailCampaignHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idl/cms.idl
* Friday, April 18, 2025 1:35:56 AM ICT
*/

public final class EmailCampaignHolder implements org.omg.CORBA.portable.Streamable
{
  public CMS.EmailCampaign value = null;

  public EmailCampaignHolder ()
  {
  }

  public EmailCampaignHolder (CMS.EmailCampaign initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CMS.EmailCampaignHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CMS.EmailCampaignHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CMS.EmailCampaignHelper.type ();
  }

}
