package CMS;

/**
* CMS/EmailMarketingServiceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idl/cms.idl
* Friday, April 18, 2025 1:35:57 AM ICT
*/

public final class EmailMarketingServiceHolder implements org.omg.CORBA.portable.Streamable
{
  public CMS.EmailMarketingService value = null;

  public EmailMarketingServiceHolder ()
  {
  }

  public EmailMarketingServiceHolder (CMS.EmailMarketingService initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CMS.EmailMarketingServiceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CMS.EmailMarketingServiceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CMS.EmailMarketingServiceHelper.type ();
  }

}
